title: Andre Castillo
description: [Master of Science in Information Technology](https://www.parchment.com/u/award/33601382c4de568df619322a6e753b4c) 
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
